CREATE DATABASE IF NOT EXISTS Project1;
USE Project1;
DROP TABLE IF EXISTS TodoList;
CREATE TABLE TodoList (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  todo TEXT NOT NULL,
  PRIMARY KEY (id)
);
CREATE USER IF NOT EXISTS 'project1'@'localhost' IDENTIFIED BY 'cs1122';
GRANT ALL PRIVILEGES ON Project1.* TO 'project1'@'localhost';
FLUSH PRIVILEGES;